CREATE TABLE IF NOT EXISTS USUARIOS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(50) NOT NULL,
    FECHA_DE_REGISTRO DATE NOT NULL,
    NUMERO_DE_TELEFONO VARCHAR(20)
);
